//
//  GameModel.swift
//  GameWynd
//
//  Created by RANA  on 23/10/24.
//

import Foundation

struct GameModel : Identifiable , Hashable {
    var id: UUID = .init()
    var name :  String
    var image : String
    var link : String
    var caption :  String
    
}

var gameList:[GameModel] = [
    GameModel(name: "Tanks Merge: Tank War Blitz", image: "Tank War Blitz", link: "https://html5.gamedistribution.com/76902964b0a84963ac23ae3ad750e8bb/?gd_sdk_referrer_url=https://gamedistribution.com/games/tanks-merge:-tank-war-blitz/", caption: "Embark on an armored adventure in Tanks Merge: Tanks to Attack on the Blitz! - a strategy game where steel giants dominate the world. Immerse yourself in a casual yet addictive tank simulation game designed for those who love war machines and inventive tactics. Have a blitz rumble and defeat all the bosses! Your mission: control a fleet of tanks, each unique in design and to defeat enemies and all bosses on the battlefield."),
    
    GameModel(name: "Gun Builder", image: "Gun Builder",link:"https://html5.gamedistribution.com/e33f54b2dda446b4b23b9a5da0c5a6ce/?gd_sdk_referrer_url=https://gamedistribution.com/games/gun-builder-1/", caption: "Defeat all incoming enemies, and protect yourself from attacks! Pick up props to strengthen your attacks, but be careful—once your health reaches zero, the mission is over. Ready to experience the action? Play now!"),
    GameModel(name: "Gun Evolution",image: "Gun Evolution", link: "https://html5.gamedistribution.com/8d125aecd58f4645bffda294deca7061/?gd_sdk_referrer_url=https://gamedistribution.com/games/gun-evolution/", caption: "Gun Evolution is both a shooting running game and a strategy merge battle game. With 3D cartoon models, you need to merge a power gun to win the battle after the finish line at each level. I recommend shooting the numbered pillars, you can claim money inside and get the items on them. When you earn enough money, you can upgrade the ATK and Speed to destroy more pillars more easily on the track. Good luck!"),
    GameModel(name: "Draw And Escape", image: "Draw And Escape", link: "https://html5.gamedistribution.com/478f36658478422c84021b62054466da/?gd_sdk_referrer_url=https://gamedistribution.com/games/draw-and-escape/", caption: "Car Games: Draw And Escape is a collection of parking puzzle games and drawing puzzle games. Draw Bridge requires you to draw a line across a defined area to help the yellow car to the finish line. When you meet the steps, you can also draw bridges to build a track to the finish line. Use your creativity to design the perfect path to win! Parking Jam 2d requires you to help all cars out of the parking lot smoothly and pay attention to the order of cars, to prevent traffic accidents."),
    GameModel(name: "Halloween Challenge", image: "Halloween Challenge", link: "https://html5.gamedistribution.com/7ec72d890bde4256b02f8222a6545b4c/?gd_sdk_referrer_url=https://gamedistribution.com/games/halloween-challenge/", caption: "Get ready for a spooky adventure in Halloween Challenge! Bats are flying through the night, carrying candy that you must protect. Your mission? Tap the bats before they escape with the sweet treats. But beware, if even one bat escapes, the game is over! With simple controls and addictive gameplay, Halloween Challenge offers a fun and fast-paced experience for players. Test your reflexes, compete for high scores, and enjoy the eerie Halloween atmosphere. How long can you defend the candy?"),
    GameModel(name: "Hidden Objects Crime Scene",image: "Hidden Objects Crime Scene", link: "https://html5.gamedistribution.com/c2342d70e2b34a94a627b9536c1fa4ac/?gd_sdk_referrer_url=https://gamedistribution.com/games/hidden-objects-crime-scene/", caption: "Keep clear! It's a police crime scene, and the evidence must not be disturbed. Engage your detective instincts and dive into Hidden Objects Crime Scene! Keep a sharp eye out for clues left behind by the perpetrator. Work fast, and you might solve the case! Can you find all the pieces of evidence? Come play now, and let's find out!"),
    GameModel(name: "Master Addiction Solitaire", image: "Master Addiction Solitaire", link: "https://html5.gamedistribution.com/7a5fd268c16543bcadfc46a314a6ded7/?gd_sdk_referrer_url=https://gamedistribution.com/games/master-addiction-solitaire/", caption: "Challenge yourself and take on this brain teaser of a solitaire game! Masterfully rearrange the cards so they end up in ascending order, from A to 6 If you need some help, there are hints, undos, and shuffle that you can use"),
    GameModel(name: "Stickman: Dinosaur arena", image: "Dinosaur arena", link: "https://html5.gamedistribution.com/555a2c0c1db14d2e8e3f50e1e9bbe149/?gd_sdk_referrer_url=https://gamedistribution.com/games/stickman:-dinosaur-arena/", caption: "Take command of a squad of dinosaurs and go into battle with them! Reinforce your squad, unlock new dinosaurs and upgrade existing ones. Go as far as possible and become a great Dino Commander!"),
    GameModel(name: "Color Rings Block Puzzle", image: "Color Rings Block Puzzle", link: "https://html5.gamedistribution.com/35082481c2cd4939b524fbdfd19c3ec6/?gd_sdk_referrer_url=https://gamedistribution.com/games/color-rings-block-puzzle/", caption: "Color Rings Block Puzzle is a fun and addictive mobile game that challenges your problem-solving skills and reflexes. The game is simple to play but difficult to master, making it perfect for both casual and hardcore gamers."),
    GameModel(name: "Crazy Hill Climbing", image: "Crazy Hill Climbing", link: "https://html5.gamedistribution.com/822814385dfb43bfbaec28e839dedeb7/?gd_sdk_referrer_url=https://gamedistribution.com/games/crazy-hill-climbing/", caption: "Get ready for the ultimate hill racing adventure in Crazy Hill Climbing! Race through steep hills, rugged terrains, and tackle challenging obstacles. With 15 unique levels and cars to unlock, upgrade your vehicles and customize your rides as you strive to conquer each track and perform daring stunts. * Use coins to upgrade your engine, tires, suspension, and more to improve performance on rough terrains * Execute daring front flips and back flips to earn extra points and boost your score"),
    GameModel(name: "Hexa puzzle", image: "Hexa puzzle", link: "https://html5.gamedistribution.com/8a0f1411e13d48bb98b756921734b248/?gd_sdk_referrer_url=https://gamedistribution.com/games/hexa-puzzle-3/", caption: "Stretch your mind and train your brain with this addictive block puzzle game. Can you solve all of the hundreds of free puzzles? Put your mind and brain to work to solve the puzzle game by placing the unique hexagon pieces neatly into the puzzle grid. Merge each hexo shaped piece into the grid one by one. Similar to Tetris, they all need to fit together to complete the puzzle. You may need more time to match all the blocks into the super perfect spot - but that's fine, there are no time limit!"),
    GameModel(name: "CRAZY VAN", image: "CRAZY VAN", link: "https://html5.gamedistribution.com/180ff7e091954817afeeebd7d2324a75/?gd_sdk_referrer_url=https://gamedistribution.com/games/crazy-van/", caption: "Operate your car to defeat zombies! Defeating zombies will earn you coins, which you can use to strengthen your car. If you kill a lot of zombies, the time limit will be added, allowing you to defeat more zombies."),
    GameModel(name: "Stunt Multiplayer Arena", image: "Stunt Multiplayer Arena", link: "https://html5.gamedistribution.com/6552bf3254b441c1baf6b4727006bd28/?gd_sdk_referrer_url=https://gamedistribution.com/games/stunt-multiplayer-arena/", caption: "Go solo in a free roam challenge where you can pull off incredible stunts like front and backflips. Navigate icy and dirt tracks as you push various vehicles to their limits. In the multiplayer derby mode, choose your vehicle—whether it's a car, truck, or van—and engage in a fierce survival derby. Compete against all other vehicles in an intense, smashing battle. Jump into the action today and see if you have what it takes to rule the arena!")
    
]
